version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2

  postgres-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: hito1
      POSTGRES_PASSWORD: 2332
      POSTGRES_USER: nuevo

    ports:
      - "5432:5432"
  app1:
    container_name: tingeso1
    image: diez2332/tingeso1
    ports:
      - "8091:8090"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/hito1
      - SPRING_DATASOURCE_USERNAME=nuevo
      - SPRING_DATASOURCE_PASSWORD=2332
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db

  app2:
    container_name: tingeso2
    image: diez2332/tingeso1
    ports:
      - "8092:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/hito1
      - SPRING_DATASOURCE_USERNAME=nuevo
      - SPRING_DATASOURCE_PASSWORD=2332
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db








