version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hito1
    ports:
      - 33061:3306
  app:
    container_name: tingeso1
    image: diez2332/tingeso1
    ports:
      - "8092:8092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/hito1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
