
pipeline{
    agent any
    tools{
        mave "maven"
    }
    stages{
        stage("Build JAR FILE"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/diegovaldes23/lab_Tingeso']])
                dir("hito1tingeso"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("hito1tingeso"){
                    sh "mvn test"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("hito1tingeso"){
                    sh "docker build -t diez2332/tingeso1"
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("hito1tingeso"){
                    withCredentials([string(credentialsId: 'dckrhubpassword', variable: 'dckpass')]) {
                        sh "docker login -u diez2332 -p ${dckpass}"
                    }
                    sh "docker push diez2332/tingeso1"
                }

            }
        }

    }
    post{
        always{
            dir("hito1tingeso"){
                sh "docker logout"
            }
        }
    }
}